name: NEUCF DEPLOYMENT

on:
  push:
    branches: [ deploy-branch ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID_NEUCF }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
